### ISSUE TITLE
Handle Professor Role

### ISSUE THREAD

**Issue by JPCMarques** [IST-Portfolios/portfolios-web#26]

**Comment by JPCMarques** [comment]
➤ João Marques commented:

Possibly a "subclass" of a regular users, programatically

**Comment by Strabox** [comment]
1. Make the user dashboard adapt to professor role

**Comment by Strabox** [comment]
Implemented in a obscure way to the devs. User class has a "hidden" type field  that can be "student", "professor" or "organisation" that determines the home dashboard layout
